from __future__ import annotations

COMBINE_PAIRS = [
    ("*Failure", "Failure", "Error Code"),
    ("Comp. suction pipe temp. (°C)", "Accumulator inlet temp. (°C)", "*Compressor Suction Temp (°C)"),
    ("Comp.1 INV stepping down cntl", "Comp.1 OC stepping down cntl", "Comp1. stepping down cntl"),
    ("Comp.2 INV stepping down cntl", "Comp.2 OC stepping down cntl", "Comp2. stepping down cntl"),
    ("EVM (Main) (pls)", "EV opening 1 (pls)", "EV Opening 1"),
    ("EVT (subcooling heat xchanger) (pls)", "EV opening 2 (pls)", "EV Opening 2"),
    ("INV comp. body temp (°C)", "Compressor surface temp. (°C)", "Compressor Surface Temp. (°C)"),
]

DAIKIN_OUTDOOR_COMMON_COLS = [
    "*Comp 1 INV working hours",
    "*Comp 2 INV working hours",
    "*Electric Power (Estimated) (kW)",
    "Ambient temperature (°C)",
    "Backup ope.",
    "Comp.1 Disch. stepping down cntl",
    "Comp.1 current (A)",
    "Comp.2 Disch. stepping down cntl",
    "Comp.2 current (A)",
    "Compressor 1(INV1)",
    "Compressor 2(INV2)",
    "Condensing Pressure (MPa)",
    "Condensing Temperature (°C)",
    "Cooling",
    "Defrost",
    "Demand state",
    "Demand stepping down cntl",
    "Disch. pipe retry",
    "Discharge pipe temp.(Comp.1) (°C)",
    "Discharge pipe temp.(Comp.2) (°C)",
    "Error Code",
    "Evaporating Pressure (MPa)",
    "Evaporating Temperature (°C)",
    "Fan 1 rotation amount (rpm)",
    "Fan 2 rotation amount (rpm)",
    "Fan step",
    "H.P. stepping down cntl",
    "HP (hp)",
    "Heat exchanger liquid pipe temp. (°C)",
    "Heating",
    "High pressure retry",
    "I/U thermostat ON capacity",
    "INV 1 rotation amount (rps)",
    "INV 2 rotation amount (rps)",
    "INV FAN current (A)",
    "INV1 Fin stepping down cntl",
    "INV1 fin temp. (°C)",
    "INV1 stand-by",
    "INV2 Fin stepping down cntl",
    "INV2 fin temp. (°C)",
    "INV2 stand-by",
    "L.P. stepping down cntl",
    "Low pressure retry",
    "Oil return",
    "Outdoor Type",
    "Outdoor ambient temperature (°C)",
    "Overheating stand-by",
    "Restart stand-by",
    "Site temperature (°C)",
    "Startup control",
    "Subcooling heat exchanger gas temp. (°C)",
    "Subcooling heat exchanger liquid temp. (°C)",
    "System Current (A)",
    "System HP (hp)",
    "System ID",
    "Target Condensing Pressure (MPa)",
    "Target Condensing T (°C)",
    "Target Evaporation Pressure (MPa)",
    "Target Evaporation T (°C)",
    "Thermostat ON",
    "Ventilation",
    "*Compressor Suction Temp (°C)",
    "Comp1. stepping down cntl",
    "Comp2. stepping down cntl",
    "EV Opening 1",
    "EV Opening 2",
    "Compressor Surface Temp. (°C)",
    "Unit_Id",
    "timestamp",
    "datetime",
]
